// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataSource() {
  return window['go']['main']['App']['GetDataSource']();
}

export function RunBacktest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RunBacktest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SetDataSource(arg1) {
  return window['go']['main']['App']['SetDataSource'](arg1);
}
