// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RunBacktest(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number):Promise<main.BacktestResult>;
